version: '3.8'
services:
  keycloak:
    container_name: keycloak
    build: .
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
    command: start-dev
    volumes:
      - ./lifeapps-theme:/opt/keycloak/themes/lifeapps
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    volumes:
      - ./postgres_data:/var/lib/postgresql/data